name = "veyrohood-xyz-api"
workers_dev = true
main = "worker.js"
compatibility_date = "2026-09-20"
compatibility_flags = ["nodejs_compat"]

[vars]
FRONTEND_URL = "https://joinveyrohood.github.io/VeyroHood-XYZ"

[[d1_databases]]
binding = "DB"
database_name = "veyrohood-db"
database_id = "9da108b5-5b86-4a13-982a-ce9bd52c6a1b"
